# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb9bfc6e7a149db9495e1596a223ec69f1db24dc577189d30802f8a6fca6c51e30d72ffbbae4678bbf2113bbcd224346cc20c39f235ce417715170dfae0b071b

test:
  secret_key_base: 304a4a429a7b7260b30fc847d38d12feabc12040a1343025d90565a375ae6548c9091121a4f2f9465a0c8c88af440ccb33296547d624e43ab7c1205599d52ad5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
